### Rename Task
PUT http://localhost:8080/rename?id=2
Content-Type: application/json

{
  "name": "learning csharp"
}

### Update Status
PUT http://localhost:8080/status?id=2
Content-Type: application/json

{
  "taskdone": true
}

### Add Task
POST http://localhost:8080/add
Content-Type: application/json

{
  "name": "learn java",
  "taskdone": false
}

###Delete Task
DELETE http://localhost:8080/delete?id=7
Content-Type: application/json

